# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xbAhvrdoWFCCHZdQkyr41ywcGtONbvYs
"""

# -*- coding: utf-8 -*-
"""app_riego.py

Versión Flask del sistema de riego con lógica difusa
"""

from flask import Flask, render_template, request
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

app = Flask(__name__)

# --- Definición de universos ---
humedad_suelo = ctrl.Antecedent(np.arange(0, 100.1, 0.1), 'humedad_suelo')
temperatura = ctrl.Antecedent(np.arange(0, 50.1, 0.1), 'temperatura')
cantidad_agua = ctrl.Consequent(np.arange(0, 10.1, 0.1), 'cantidad_agua')

# --- Funciones de membresía ---
humedad_suelo['seca'] = fuzz.trapmf(humedad_suelo.universe, [0, 0, 15, 40])
humedad_suelo['optima'] = fuzz.trapmf(humedad_suelo.universe, [30, 50, 65, 80])
humedad_suelo['saturada'] = fuzz.trapmf(humedad_suelo.universe, [70, 90, 100, 100])

temperatura['fria'] = fuzz.trapmf(temperatura.universe, [0, 0, 10, 20])
temperatura['templada'] = fuzz.trapmf(temperatura.universe, [15, 25, 30, 40])
temperatura['caliente'] = fuzz.trapmf(temperatura.universe, [35, 45, 50, 50])

cantidad_agua['casi_nada'] = fuzz.trapmf(cantidad_agua.universe, [0, 0, 0.5, 2])
cantidad_agua['poca'] = fuzz.trapmf(cantidad_agua.universe, [1, 3, 4, 6])
cantidad_agua['media'] = fuzz.trapmf(cantidad_agua.universe, [5, 7, 8, 9])
cantidad_agua['mucha'] = fuzz.trapmf(cantidad_agua.universe, [8, 9.5, 10, 10])

# --- Reglas difusas ---
rules = [
    ctrl.Rule(humedad_suelo['seca'] & temperatura['fria'], cantidad_agua['poca']),
    ctrl.Rule(humedad_suelo['seca'] & temperatura['templada'], cantidad_agua['media']),
    ctrl.Rule(humedad_suelo['seca'] & temperatura['caliente'], cantidad_agua['mucha']),

    ctrl.Rule(humedad_suelo['optima'] & temperatura['fria'], cantidad_agua['casi_nada']),
    ctrl.Rule(humedad_suelo['optima'] & temperatura['templada'], cantidad_agua['poca']),
    ctrl.Rule(humedad_suelo['optima'] & temperatura['caliente'], cantidad_agua['media']),

    ctrl.Rule(humedad_suelo['saturada'] & temperatura['fria'], cantidad_agua['casi_nada']),
    ctrl.Rule(humedad_suelo['saturada'] & temperatura['templada'], cantidad_agua['casi_nada']),
    ctrl.Rule(humedad_suelo['saturada'] & temperatura['caliente'], cantidad_agua['poca'])
]

riego_ctrl = ctrl.ControlSystem(rules)
riego = ctrl.ControlSystemSimulation(riego_ctrl)

# --- Rutas Flask ---
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/calcular', methods=['POST'])
def calcular():
    try:
        humedad = float(request.form['humedad'])
        temperatura_val = float(request.form['temperatura'])

        riego.input['humedad_suelo'] = humedad
        riego.input['temperatura'] = temperatura_val
        riego.compute()

        agua_sugerida = round(riego.output['cantidad_agua'], 2)
        agua_sugerida = max(0, agua_sugerida)

        return render_template('index.html', resultado=agua_sugerida)
    except Exception as e:
        return render_template('index.html', resultado=f"Error: {e}")

# --- Ejecutar servidor ---
if __name__ == '__main__':
    app.run(debug=True)